### ISSUE TITLE
Add more to `.uns` for raw and processed versions

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/rna-data-products#13]
Additional information that should be stored in `.uns`:
- Creation time
- List or set of datasets used to create that data product (HuBMAP IDs)
  - Could be computed right before saving the raw object, as `adata.uns['datasets'] = list(set(adata.obs.hubmap_id))`` or something
- Cell type counts
  - Might not be the same between the raw and analyzed versions, so compute counts in the same way for both

**Comment by pennycuda** [comment]
Completed :) not merged into main yet
