### ISSUE TITLE
Update organ-types.yaml

### ISSUE THREAD

**Issue by SFD5311** [hubmapconsortium/rna-data-products#2]
Organ-types.yaml contains mappings from two letter organ codes to more human-friendly names of organs.  Update this mapping to include new to HuBMAP organs.

**Comment by lchoy** [comment]
An organ mapping is provided by the Ontology API, also known as UBKG. Could this be used to avoid maintaining multiple mappings? 

- [ SmartAPI documentation](https://smart-api.info/ui/d10ff85265d8b749fbe3ad7b51d0bf0a#/default/get_organ_by_code)
- https://github.com/hubmapconsortium/ontology-api

@AlanSimmons @shirey

**Comment by AlanSimmons** [comment]
All current organs: https://ontology.api.hubmapconsortium.org/organs?application_context=HUBMAP
All current organs by 2-character code: https://ontology.api.hubmapconsortium.org/organs/by-code?application_context=HUBMAP

**Comment by AlanSimmons** [comment]
All of the organs listed in @pennycuda 's original message are currently coded in the UBKG, for both HubMAP and SenNet.

**Comment by pennycuda** [comment]
Thanks @AlanSimmons @lchoy !
